version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/flask/Dockerfile
        command: /start
        container_name: flask-api
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        env_file:
            - ./.envs/.local/.flask
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
            - redis
        networks:
            - flask-starter-api-live

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        container_name: postgres
        # volumes:
        #     - local_postgres_data:/var/lib/postgresql/data
        #     - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - flask-starter-api-live
    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - flask-starter-api-live
    redis:
        image: redis:6-alpine
        container_name: redis
        networks:
            - flask-starter-api-live

    nginx:
        restart: always
        depends_on:
            - api
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - flask-starter-api-live 


networks:
    flask-starter-api-live:
        driver: bridge

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume:
    media_volume: